"""add notes to interviews

Revision ID: 9a3a302869e5
Revises: de3a44dc1eed
Create Date: 2026-08-19 04:49:55.739417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9a3a302869e5'
down_revision: Union[str, Sequence[str], None] = 'de3a44dc1eed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matches')
    op.create_foreign_key(None, 'interviews', 'job_descriptions', ['job_description_id'], ['id'])
    op.create_foreign_key(None, 'interviews', 'resumes', ['resume_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'interviews', type_='foreignkey')
    op.drop_constraint(None, 'interviews', type_='foreignkey')
    op.create_table('matches',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('resume_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('jd_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('similarity_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('matched_skills', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('missing_skills', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['jd_id'], ['job_descriptions.id'], name='matches_jd_id_fkey'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], name='matches_resume_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='matches_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='matches_pkey')
    )
    # ### end Alembic commands ###
